version: "3.9"  # optional since v1.27.0
services:
  article_server:
    container_name: article_server
    image: ultradx/article_server
    environment:
        NODE_ENV: production
    ports:
      - "5000:5000"    
    volumes:
      - .:/code
      - logvolume01:/var/log      
    links:
      - mongodb
    networks:
      - back-end
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      - back-end

networks:
    back-end:

volumes:
    logvolume01: {}
    data: {}